# Generated by Django 3.2.6 on 2021-08-13 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_user',
            fields=[
                ('year_of_passing', models.CharField(max_length=4)),
                ('last_studied_class', models.CharField(max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
