# Generated by Django 3.2.6 on 2021-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210813_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
