# Generated by Django 3.2.6 on 2021-08-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210813_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_user',
            old_name='father_name',
            new_name="Father's Name",
        ),
    ]
