# Generated by Django 3.2.6 on 2021-08-13 12:43

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', "0005_rename_father_name_temp_user_father's name"),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name="Father's Name",
            field=models.CharField(max_length=200, null=True, validators=[register.models.string_cheker]),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='last_studied_class',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='name',
            field=models.CharField(max_length=200, null=True, validators=[register.models.string_cheker]),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='profession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='year_of_passing',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
