# Generated by Django 3.2.6 on 2021-08-14 09:22

from django.db import migrations, models
import register.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210813_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_acc',
            fields=[
                ('name', models.CharField(max_length=200, null=True, validators=[register.models.string_cheker])),
                ("Father's Name", models.CharField(max_length=200, null=True, validators=[register.models.string_cheker])),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('year_of_passing', models.CharField(max_length=4, null=True)),
                ('last_studied_class', models.CharField(max_length=2, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
