# Generated by Django 3.2.6 on 2021-08-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_user_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp_user',
            old_name="Father's Name",
            new_name='father_name',
        ),
    ]
