# Generated by Django 3.2.6 on 2021-08-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', "0008_rename_father's name_temp_user_father_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_acc',
            old_name="Father's Name",
            new_name='father_name',
        ),
    ]
