# Generated by Django 3.2.6 on 2021-08-15 10:32

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', "0009_rename_father's name_user_acc_father_name"),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_user',
            name='its_id',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[register.models.its_check]),
        ),
        migrations.AddField(
            model_name='user_acc',
            name='its_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
