# Generated by Django 3.2.6 on 2021-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20210815_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='its_id',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
