# Generated by Django 3.2.6 on 2021-08-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20210824_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_user',
            name='child_in_msb',
            field=models.BooleanField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='temp_user',
            name='maritial_status',
            field=models.CharField(choices=[('married', 'Married'), ('un-married', 'Un Married')], max_length=20, null=True),
        ),
    ]
